apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend-quiz-app
  namespace: quiz
  labels:
    app: frontend-quiz-app

spec: 
  replicas: 1
  selector:
    matchLabels:
      app: frontend-quiz-app 
  template:
    metadata: 
      labels:
        app: frontend-quiz-app  
    spec:
      containers:
      - name: frontend-quiz-app
        image: 035093205970.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
        env:
        - name: VITE_REACT_APP_API_URL
          value: "http://backend-quiz-app:3000/api/questions"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-quiz-app
  namespace: quiz
spec:
  selector:
    app: frontend-quiz-app
  ports:
    - protocol: TCP
      port: 8080

