apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend-quiz-app
  labels:
    app: frontend-quiz-app

spec: 
  replicas: 1
  selector:
    matchLabels:
      app: frontend-quiz-app 
  template:
    metadata: 
      labels:
        app: frontend-quiz-app  
    spec:
      containers:
      - name: frontend-quiz-app
        image: 
        ports: 
        - containerPort: 8000 

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-quiz-app
spec:
  selector:
    app: frontend-quiz-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

